# Computational Homology of Simplicial Complexes

### Python Implementation of Boundary Operators and Betti Numbers

**Author:** Mansi Vishwakarma  
**Tools:** Python, NumPy

## Project Overview

This project develops a Python implementation of simplicial homology
using boundary operators, boundary matrices, and linear algebra.

The implementation constructs finite simplicial complexes, computes
their boundary matrices, verifies the fundamental property

$\partial_{k-1}\circ\partial_k=0$

and computes Betti numbers for simple examples.

The project begins with a basic triangle implementation and then
generalizes the construction to arbitrary simplices and finite
simplicial complexes.

In [ ]:
import numpy as np
from itertools import combinations

## 1. Mathematical Background

### 1.1 Simplicial Complexes
A simplex is the simplest building block of a simplicial complex.
A vertex is a $0$-simplex, an edge is a $1$-simplex, a triangle is a
$2$-simplex, and a tetrahedron is a $3$-simplex.

**A simplicial complex $K$ is a collection of simplices such that every
face of a simplex in $K$ is also contained in $K$.**

For example, a filled triangle contains three vertices, three edges,
and one triangular face.

### 1.2 Chain Groups

For a simplicial complex $K$, let $C_k(K)$ denote the $k$-th chain
group. It is generated by the $k$-dimensional simplices of $K$.

For example,

$C_0(K) = \text{span of vertices}$

$C_1(K) = \text{span of edges}$

and

$C_2(K) = \text{span of triangular faces}$

The chain groups provide the algebraic structure needed to define
boundary maps and homology.

### 1.3 Boundary Maps

The boundary map

$\partial_k:C_k(K)\rightarrow C_{k-1}(K)$

maps each $k$-dimensional simplex to its oriented boundary.

For an oriented $k$-simplex,

$\boxed{\partial[v_0,\ldots,v_k]
=
\sum_{i=0}^{k}(-1)^i
[v_0,\ldots,\widehat{v_i},\ldots,v_k]}$

Here, $\widehat{v_i}$ means that the vertex $v_i$ is removed.

An important property of boundary maps is

$\boxed{\partial_{k-1}\circ\partial_k=0}$

This means that the boundary of a boundary is always zero.

### 1.4 Homology Groups

The $k$-th homology group measures cycles that are not boundaries.

It is defined by:

$\boxed{H_k(K)=
\frac{\ker(\partial_k)}
{\operatorname{im}(\partial_{k+1})}}$

where:
 - $ker(\partial_k)$ is called the space of $k$-cycles, denoted as $Z_k$ .
 - $im(\partial_{k+1})$ is called the space of $k$-boundaries, often denoted as $B_k$ .

Thus, homology identifies cycles that are not boundaries of higher
dimensional simplices.

### 1.5 Betti Numbers

The $k$-th Betti number $\beta_k$ is the dimension of the $k$-th
homology group.

It can be computed using

$\beta_k
=
\dim(\ker \partial_k)
-
\dim(\operatorname{im}\partial_{k+1}).$

Using the rank-nullity theorem, this becomes

$\boxed{
\beta_k
=
\dim C_k
-
\operatorname{rank}(\partial_k)
-
\operatorname{rank}(\partial_{k+1})
}$

Betti numbers give numerical information about the topology of a
simplicial complex. In particular, $\beta_0$ counts connected
components, while $\beta_1$ measures independent one-dimensional
holes.

## 2. Implementation

The mathematical concepts introduced above are implemented in Python
using NumPy and basic data structures such as lists and tuples.

The implementation is developed in stages. It begins with a simple
triangle example and then constructs a general framework for finite
simplicial complexes.

The main steps are:

1. Represent simplices and simplicial complexes.
2. Construct boundary operators and boundary matrices.
3. Verify the boundary property.
4. Compute Betti numbers.

### 2.1 Basic Simplex Representation

A simplex is represented as a tuple containing its vertices. For example,

\[ (0,1,2) \]

represents a triangle, while

\[ (0,1,2,3) \]

represents a tetrahedron.

The same representation is used for simplices of different dimensions.

### 2.2 Initial Triangle Implementation

We first implement the boundary matrices for a simple filled triangle.

The vertices, edges, and the triangular face are represented explicitly.
The boundary matrices $\partial_1$ and $\partial_2$ are then constructed
using the chosen orientations.

We then verify the relation

$\partial_1 \circ \partial_2=0$

and compute the Betti numbers of the triangle.

In [ ]:
svertices = [0, 1, 2]
edges = [(0, 1), (1, 2), (2, 0)]
faces = [(0, 1, 2)]

print("Vertices:", vertices)
print("Edges:", edges)
print("Faces:", faces)


def boundary_matrix_1(vertices, edges):
    matrix = np.zeros((len(vertices), len(edges)), dtype=int)

    for j, edge in enumerate(edges):
        start, end = edge

        matrix[vertices.index(start), j] = -1
        matrix[vertices.index(end), j] = 1

    return matrix


def oriented_edge_index(edges, edge):
    if edge in edges:
        return edges.index(edge), 1

    reversed_edge = (edge[1], edge[0])

    if reversed_edge in edges:
        return edges.index(reversed_edge), -1

    return None, 0


def boundary_matrix_2(edges, faces):
    matrix = np.zeros((len(edges), len(faces)), dtype=int)

    for i, face in enumerate(faces):
        v0, v1, v2 = face

        boundary_edges = [
            (v0, v1),
            (v1, v2),
            (v2, v0)]

        for edge in boundary_edges:
            index, coefficient = oriented_edge_index(edges, edge)
            matrix[index, i] = coefficient

    return matrix


boundary_1 = boundary_matrix_1(vertices, edges)
boundary_2 = boundary_matrix_2(edges, faces)

print("\nBoundary matrix ∂₁:")
print(boundary_1)

print("\nBoundary matrix ∂₂:")
print(boundary_2)

result = boundary_1 @ boundary_2

print("\n∂₁ @ ∂₂:")
print(result)

rank_1 = np.linalg.matrix_rank(boundary_1)
rank_2 = np.linalg.matrix_rank(boundary_2)

beta_0 = len(vertices) - rank_1
beta_1 = len(edges) - rank_1 - rank_2
beta_2 = len(faces) - rank_2

print("\nBetti numbers:")
print("β₀ =", beta_0)
print("β₁ =", beta_1)
print("β₂ =", beta_2)

Vertices: [0, 1, 2]
Edges: [(0, 1), (1, 2), (2, 0)]
Faces: [(0, 1, 2)]

Boundary matrix ∂₁:
[[-1  0  1]
 [ 1 -1  0]
 [ 0  1 -1]]

Boundary matrix ∂₂:
[[1]
 [1]
 [1]]

∂₁ @ ∂₂:
[[0]
 [0]
 [0]]

Betti numbers:
β₀ = 1
β₁ = 0
β₂ = 0


### 2.3 GENERAL BOUNDARY OPERATOR FOR ARBITRARY SIMPLICES
#### Mathematical Formulation

The boundary of an oriented $k$-simplex is given by

$\boxed{\partial[v_0,\ldots,v_k]=\sum_{i=0}^{k}(-1)^i[v_0,\ldots,\widehat{v_i},\ldots,v_k]}$

This formula removes one vertex at a time and assigns alternating
coefficients $+1$ and $-1$.

Unlike the earlier implementation, which was specifically designed
for triangles, the following implementation works for simplices of
arbitrary dimensions.

#### Python Implementation

In [ ]:
def boundary(simplex):
    """
    Compute the oriented boundary of a simplex.

    Each face is obtained by removing one vertex, with
    alternating signs.
    """
    result = []

    for i in range(len(simplex)):
        face = simplex[:i] + simplex[i+1:]
        coefficient = (-1)**i
        result.append((coefficient, face))

    return result


# Triangle test
triangle = (0, 1, 2)

print("Boundary of triangle:")
print(boundary(triangle))


# Tetrahedron test
tetrahedron = (0, 1, 2, 3)

print("\nBoundary of tetrahedron:")
print(boundary(tetrahedron))

Boundary of triangle:
[(1, (1, 2)), (-1, (0, 2)), (1, (0, 1))]

Boundary of tetrahedron:
[(1, (1, 2, 3)), (-1, (0, 2, 3)), (1, (0, 1, 3)), (-1, (0, 1, 2))]


### 2.4 Generalization to Simplicial Complexes

A simplicial complex may contain several simplices of different
dimensions.

 Therefore, the implementation should automatically
generate all faces of the given simplices.

The following function constructs a simplicial complex from a
**collection of maximal simplices** and **includes all of their faces.**

In [ ]:
def simplicial_complex(maximal_simplices):
    K = set()

    for simplex in maximal_simplices:
        for r in range(1, len(simplex) + 1):
            for face in combinations(simplex, r):
                K.add(face)

    return sorted(K, key=lambda x: (len(x), x))


# Example: a filled triangle
maximal_simplices = [(0, 1, 2)]

K = simplicial_complex(maximal_simplices)

print("Simplicial complex:")
print(K)


Simplicial complex:
[(0,), (1,), (2,), (0, 1), (0, 2), (1, 2), (0, 1, 2)]


### 2.5 Extracting Simplices by Dimension

For the construction of boundary matrices, we need to **identify the
simplices of each dimension.**

The following function extracts all $k$-dimensional simplices from a
simplicial complex. Since a $k$-simplex contains $k+1$ vertices, we
select simplices whose length is $k+1$.

In [ ]:
def simplices_of_dimension(K, dimension):
    return [
        simplex for simplex in K
        if len(simplex) == dimension + 1
    ]


print("C₀ generators:", simplices_of_dimension(K, 0))
print("C₁ generators:", simplices_of_dimension(K, 1))
print("C₂ generators:", simplices_of_dimension(K, 2))

C₀ generators: [(0,), (1,), (2,)]
C₁ generators: [(0, 1), (0, 2), (1, 2)]
C₂ generators: [(0, 1, 2)]


### 2.6 General Boundary Matrices

The boundary maps can be represented computationally by matrices.

For a fixed dimension $k$, the columns of the boundary matrix
$\partial_k$ correspond to the $k$-simplices, while the rows correspond
to the $(k-1)$-simplices.

The entries of the matrix are determined by the orientation of the
simplices and the alternating signs in the boundary formula.

The following function constructs the boundary matrix for any
dimension for which the required simplices are present.

In [ ]:
def boundary_matrix(K, k):
    k_simplices = simplices_of_dimension(K, k)
    lower_simplices = simplices_of_dimension(K, k - 1)

    matrix = np.zeros(
        (len(lower_simplices), len(k_simplices)),
        dtype=int
    )

    for j, simplex in enumerate(k_simplices):

        for i in range(len(simplex)):
            face = simplex[:i] + simplex[i+1:]
            coefficient = (-1)**i

            row = lower_simplices.index(face)
            matrix[row, j] = coefficient

    return matrix


boundary_1 = boundary_matrix(K, 1)
boundary_2 = boundary_matrix(K, 2)

print("Boundary matrix ∂₁:")
print(boundary_1)

print("\nBoundary matrix ∂₂:")
print(boundary_2)


Boundary matrix ∂₁:
[[-1 -1  0]
 [ 1  0 -1]
 [ 0  1  1]]

Boundary matrix ∂₂:
[[ 1]
 [-1]
 [ 1]]


### 2.7 Verification of the Boundary Property

A fundamental property of the boundary maps is

$\partial_{k-1}\circ\partial_k=0$

For the two-dimensional case, this becomes

$\partial_1\ \circ\partial_2=0$

We verify this computationally by multiplying the corresponding
boundary matrices.

In [ ]:
result = boundary_1 @ boundary_2

print("∂₁ @ ∂₂ =")
print(result)

∂₁ @ ∂₂ =
[[0]
 [0]
 [0]]


### 2.8 Betti Number Computation

The Betti numbers are computed from the dimensions of the chain groups
and the ranks of the boundary matrices.

Using the rank-nullity theorem,

$\beta_k=\dim C_k-\operatorname{rank}(\partial_k)-\operatorname{rank}(\partial_{k+1})$


The following function computes the Betti number for a given dimension
of a simplicial complex.

In [ ]:
def betti_number(K, k):
    dim_Ck = len(simplices_of_dimension(K, k))

    rank_k = 0
    rank_k_plus_1 = 0

    if k > 0:
        boundary_k = boundary_matrix(K, k)
        rank_k = np.linalg.matrix_rank(boundary_k)

    if k + 1 <= max(len(s) for s in K) - 1:
        boundary_k_plus_1 = boundary_matrix(K, k + 1)
        rank_k_plus_1 = np.linalg.matrix_rank(boundary_k_plus_1)

    return dim_Ck - rank_k - rank_k_plus_1


print("Betti numbers:")

for k in range(3):
    print("β", k, "=", betti_number(K, k))


Betti numbers:
β 0 = 1
β 1 = 0
β 2 = 0


## 3. Results

The implementation was tested on two different simplicial complexes:
**a filled triangle and the boundary of a triangle.**

These examples demonstrate that the same general implementation can
compute Betti numbers for simplicial complexes with different
dimensions and topological structures.

### 3.1 Filled Triangle

A filled triangle consists of three vertices, three edges, and one
two-dimensional face.

The computed Betti numbers are


$(\beta_0,\beta_1,\beta_2)=(1,0,0)$

Thus, the complex has one connected component and no one-dimensional
or two-dimensional holes.

In [ ]:
# Example 1: Filled triangle

filled_triangle = [(0, 1, 2)]

K_triangle = simplicial_complex(filled_triangle)

print("Filled triangle:")
print("β₀ =", betti_number(K_triangle, 0))
print("β₁ =", betti_number(K_triangle, 1))
print("β₂ =", betti_number(K_triangle, 2))

Filled triangle:
β₀ = 1
β₁ = 0
β₂ = 0


### 3.2 Triangle Boundary

The interior of the triangle is removed, leaving only its three edges.
The edges form a closed loop, which creates one one-dimensional hole.

The computed Betti numbers are

$(\beta_0,\beta_1)=(1,1)$

Here, $\beta_0=1$ shows that the complex is connected, while
$\beta_1=1$ detects the one-dimensional hole.

In [ ]:
# Example 2: Boundary of a triangle

triangle_boundary = [
    (0, 1),
    (1, 2),
    (2, 0)
]

K_boundary = simplicial_complex(triangle_boundary)

print("Triangle boundary:")
print("β₀ =", betti_number(K_boundary, 0))
print("β₁ =", betti_number(K_boundary, 1))

Triangle boundary:
β₀ = 1
β₁ = 1


### 3.3 Summary of Results

The computed Betti numbers for the tested simplicial complexes are
summarized below.

| Simplicial Complex | $\beta_0$ | $\beta_1$ | $\beta_2$ | Interpretation |
|---|---:|---:|---:|---|
| Filled triangle | 1 | 0 | 0 | One connected component, no holes |
| Triangle boundary | 1 | 1 | 0 | One connected component, one 1-dimensional hole |

These results agree with the expected topology of the examples and
provide a computational check of the implementation.

## 4. Discussion

The computational results show that the implementation correctly
captures basic topological properties of simplicial complexes.

For the filled triangle, the three edges form a cycle, but this cycle
is the boundary of the two-dimensional simplex. Therefore, **it does not
produce a non-trivial one-dimensional homology class**, giving
$\beta_1=0$.

For the triangle boundary, the two-dimensional face is absent.   Therefore,
the three edges form a closed loop that is not the boundary of any
two-dimensional simplex in the complex. This produces **one
non-trivial one-dimensional homology class**, giving $\beta_1=1$.

Thus, the computation of Betti numbers reflects the difference between a filled region and its boundary.

## 5. Limitations and Future Work

The current implementation provides a basic computational framework for
simplicial homology using boundary matrices and linear algebra.

The implementation works with finite simplicial complexes and uses
NumPy for the matrix computations. The examples considered in this project are small, and the implementation has not been tested or optimized for very large simplicial complexes.

### Future Work

Possible future extensions include:

- **Computing homology in higher dimensions.**
- **Testing the implementation on larger and more complicated
  simplicial complexes.**
- **Improving the efficiency of boundary-matrix construction.**
- Adding visualization of simplicial complexes and their homology.
- Computing additional topological invariants.
- Comparing the implementation with established computational
  topology software.

These extensions would allow the implementation to be applied to more
complex computational topology problems.

## 6. Conclusion

This project developed a **Python-based implementation of simplicial
homology** using boundary matrices and linear algebra.

The implementation was first tested on simple examples and then
generalized to **arbitrary simplices and finite simplicial complexes**.

The fundamental property

$\boxed{\partial_{k-1}\circ\partial_k=0}$

was verified computationally, and **Betti numbers were computed**
for different examples.

The results show that the implementation can identify basic
topological features such as **connected components and
one-dimensional holes**.

Overall, this project provides a computational introduction to
simplicial homology and demonstrates the connection between
**algebraic topology and practical computation**.